export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const LOCAL_POLL_CREATED = "LOCAL_POLL_CREATED";
export const LOCAL_POLL_SAVED = "LOCAL_POLL_SAVED";
export const LOCAL_POLL_SAVE_FAILED = "LOCAL_POLL_SAVE_FAILED";